<a href="https://colab.research.google.com/github/yashshahi9/One_hot_encoding/blob/main/one_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Loading the data into the dataframe

In [3]:
df = pd.read_csv("/content/cars.csv")

In [ ]:
df.head(5)

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [ ]:
df["brand"].nunique()

32

In [ ]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [ ]:
df['fuel'].nunique()

4

In [ ]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [ ]:
df['owner'].nunique()

5

## One-Hot-Encoding using pandas

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# K-1 OHE

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [ ]:
df.head(5)

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
pd.get_dummies(df,columns=['brand'],drop_first=True)

,km_driven,fuel,owner,selling_price,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,...,brand_Mitsubishi,brand_Nissan,brand_Opel,brand_Peugeot,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,145500,Diesel,First Owner,450000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,120000,Diesel,Second Owner,370000,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,140000,Petrol,Third Owner,158000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,127000,Diesel,First Owner,225000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,120000,Petrol,First Owner,130000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,110000,Petrol,First Owner,320000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8124,119000,Diesel,Fourth & Above Owner,135000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8125,120000,Diesel,First Owner,382000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8126,25000,Diesel,First Owner,290000,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
8127,25000,Diesel,First Owner,290000,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [ ]:
X = df.drop('selling_price', axis=1)
y = df['selling_price']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
categorical_cols = ['brand','fuel','owner']

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cats', OneHotEncoder(
            drop = 'first',
            handle_unknown='infrequent_if_exist',
            min_frequency=100,
            sparse_output=False
        ), categorical_cols)
    ],
    remainder='passthrough'
)

In [ ]:
X_encoded = preprocessor.fit_transform(X_train)

In [ ]:
columns = preprocessor.get_feature_names_out()
df_encoded = pd.DataFrame(X_encoded, columns=columns)

print(df_encoded.head())

   cats__brand_Ford  cats__brand_Honda  cats__brand_Hyundai  \
0               0.0                0.0                  0.0
1               0.0                1.0                  0.0
2               0.0                0.0                  1.0
3               0.0                0.0                  0.0
4               0.0                0.0                  0.0

   cats__brand_Mahindra  cats__brand_Maruti  cats__brand_Renault  \
0                   0.0                 0.0                  0.0
1                   0.0                 0.0                  0.0
2                   0.0                 0.0                  0.0
3                   0.0                 1.0                  0.0
4                   0.0                 1.0                  0.0

   cats__brand_Tata  cats__brand_Toyota  cats__brand_Volkswagen  \
0               1.0                 0.0                     0.0
1               0.0                 0.0                     0.0
2               0.0                 0.0                     0.0
3               0.0                 0.0                     0.0
4               0.0                 0.0                     0.0

   cats__brand_infrequent_sklearn  cats__fuel_Petrol  \
0                             0.0                1.0
1                             0.0                1.0
2                             0.0                0.0
3                             0.0                0.0
4                             0.0                1.0

   cats__fuel_infrequent_sklearn  cats__owner_Fourth & Above Owner  \
0                            0.0                               0.0
1                            0.0                               0.0
2                            0.0                               1.0
3                            0.0                               0.0
4                            0.0                               0.0

   cats__owner_Second Owner  cats__owner_Third Owner  \
0                       0.0                      0.0
1                       1.0                      0.0
2                       0.0                      0.0
3                       1.0                      0.0
4                       0.0                      0.0

   cats__owner_infrequent_sklearn  remainder__km_driven
0                             0.0                2560.0
1                             0.0               80000.0
2                             0.0              150000.0
3                             0.0              120000.0
4                             0.0               25000.0

In [ ]:
df_encoded.shape

(6502, 17)

In [ ]:
!ls /content

cars.csv  One_hot_Encoding  sample_data

In [ ]:
!ls -l /content

total 328
-rw-r--r-- 1 root root 324046 Feb 11 06:11 cars.csv
drwxr-xr-x 3 root root   4096 Feb 11 06:47 One_hot_Encoding
drwxr-xr-x 1 root root   4096 Jan 16 14:24 sample_data